def get(url: str, **kwargs) -> dict: ...

class Client:
    def __init__(self, headers: dict=None, **kwargs) -> None: ...
    def get(self, url: str, headers: dict=None, **kwargs) -> dict: ...
    def request(self, method: str, url: str, headers: dict=None, **kwargs) -> dict: ...

class Response:
    def __init__(self, **kwargs) -> None: ...
    def json(self) -> dict: ...
    def text(self) -> str: ...
    def raise_for_status(self) -> None: ...
    def status_code(self) -> int: ...
    def headers(self) -> dict: ...